#version 430
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct SPIRV_Cross_Input
{
    uvec3 _RESERVED_IDENTIFIER_FIXUP_gl_GlobalInvocationID;
};

layout(binding = 0, std430) buffer TransformData
{
    uint _data[];
} TransformData_1;

uvec3 _RESERVED_IDENTIFIER_FIXUP_gl_GlobalInvocationID;

void StoreTransform(uint index, vec3 translation)
{
    uint base = index * 80u;
    int byteAddrTemp = int((base + 0u) >> uint(2));
    TransformData_1._data[byteAddrTemp] = 1u;
    int byteAddrTemp_1 = int((base + 4u) >> uint(2));
    TransformData_1._data[byteAddrTemp_1] = index;
    int byteAddrTemp_2 = int((base + 8u) >> uint(2));
    TransformData_1._data[byteAddrTemp_2] = floatBitsToUint(0.0);
    int byteAddrTemp_3 = int((base + 12u) >> uint(2));
    TransformData_1._data[byteAddrTemp_3] = 0u;
    int byteAddrTemp_4 = int((base + 16u) >> uint(2));
    TransformData_1._data[byteAddrTemp_4] = 0u;
    int byteAddrTemp_5 = int((base + 20u) >> uint(2));
    TransformData_1._data[byteAddrTemp_5] = 0u;
    int byteAddrTemp_6 = int((base + 24u) >> uint(2));
    TransformData_1._data[byteAddrTemp_6] = 0u;
    TransformData_1._data[byteAddrTemp_6 + 1] = 0u;
    int byteAddrTemp_7 = int((base + 32u) >> uint(2));
    TransformData_1._data[byteAddrTemp_7] = floatBitsToUint(1.0);
    int byteAddrTemp_8 = int((base + 36u) >> uint(2));
    TransformData_1._data[byteAddrTemp_8] = floatBitsToUint(0.0);
    int byteAddrTemp_9 = int((base + 40u) >> uint(2));
    TransformData_1._data[byteAddrTemp_9] = floatBitsToUint(0.0);
    int byteAddrTemp_10 = int((base + 44u) >> uint(2));
    TransformData_1._data[byteAddrTemp_10] = floatBitsToUint(translation.x);
    int byteAddrTemp_11 = int((base + 48u) >> uint(2));
    TransformData_1._data[byteAddrTemp_11] = floatBitsToUint(0.0);
    int byteAddrTemp_12 = int((base + 52u) >> uint(2));
    TransformData_1._data[byteAddrTemp_12] = floatBitsToUint(1.0);
    int byteAddrTemp_13 = int((base + 56u) >> uint(2));
    TransformData_1._data[byteAddrTemp_13] = floatBitsToUint(0.0);
    int byteAddrTemp_14 = int((base + 60u) >> uint(2));
    TransformData_1._data[byteAddrTemp_14] = floatBitsToUint(translation.y);
    int byteAddrTemp_15 = int((base + 64u) >> uint(2));
    TransformData_1._data[byteAddrTemp_15] = floatBitsToUint(0.0);
    int byteAddrTemp_16 = int((base + 68u) >> uint(2));
    TransformData_1._data[byteAddrTemp_16] = floatBitsToUint(0.0);
    int byteAddrTemp_17 = int((base + 72u) >> uint(2));
    TransformData_1._data[byteAddrTemp_17] = floatBitsToUint(1.0);
    int byteAddrTemp_18 = int((base + 76u) >> uint(2));
    TransformData_1._data[byteAddrTemp_18] = floatBitsToUint(translation.z);
}

void _main(uvec3 dtid)
{
    uint index = dtid.x;
    if (index == 0u)
    {
        uint param = index;
        vec3 param_1 = vec3(-0.3499999940395355224609375, 0.0, 0.0);
        StoreTransform(param, param_1);
    }
    else
    {
        if (index == 1u)
        {
            uint param_2 = index;
            vec3 param_3 = vec3(0.3499999940395355224609375, 0.0, 0.0);
            StoreTransform(param_2, param_3);
        }
    }
}

void comp_main()
{
    uvec3 dtid = _RESERVED_IDENTIFIER_FIXUP_gl_GlobalInvocationID;
    uvec3 param = dtid;
    _main(param);
}

void _main(SPIRV_Cross_Input stage_input)
{
    _RESERVED_IDENTIFIER_FIXUP_gl_GlobalInvocationID = stage_input._RESERVED_IDENTIFIER_FIXUP_gl_GlobalInvocationID;
    comp_main();
}

void main()
{
    SPIRV_Cross_Input stage_input;
    stage_input._RESERVED_IDENTIFIER_FIXUP_gl_GlobalInvocationID = gl_GlobalInvocationID;
    SPIRV_Cross_Input param = stage_input;
    _main(param);
}
